language: python
python:
    - "3.5"
    - "3.6"
    - "3.7"
    - "3.8"
    - "3.9-dev"
    - "pypy3.5"
    - "pypy3"
matrix:
  allow_failures:
    - python: "3.9-dev"
install:
    - pip install --upgrade -r requirements-dev.txt
    # mypy can't be installed on pypy
    - if [[ "${TRAVIS_PYTHON_VERSION}" != "pypy"* ]] ; then pip install mypy ; fi
    - if [[ "${TRAVIS_PYTHON_VERSION}" != *"3.5"* && "${TRAVIS_PYTHON_VERSION}" != "pypy"* ]] ; then
        pip install black ; fi
script:
    # no IPv6 support in Travis :(
    - SKIP_IPV6=1 make ci
after_success:
    - coveralls
